OIDC Update & Change State API methods
hashicorp/boundary pull request #1000
Opened 2021-03-15 17:31 UTC by talanknight

2021-03-17 14:42 UTC, jimlambrt requested changes
Looks great.  Just a few comments/suggestions.

2021-03-17 15:41 UTC, talanknight commented on internal/proto/local/controller/storage/auth/password/store/v1/password.proto
> +  string name = 4 [(custom_options.v1.mask_mapping) = {this:"Name" that: "name"}];
It depends on how the repo implements the mask check.  The [pw auth method](https://github.com/hashicorp/boundary/blob/5162cc4570dfe19a74a4aa4f5f09f54b2225a595/internal/auth/password/repository_authmethod.go#L206) uses strings.EqualFold,  the oidc [auth method repo](https://github.com/hashicorp/boundary/blob/5162cc4570dfe19a74a4aa4f5f09f54b2225a595/internal/db/common/update.go#L147) uses checking map key presence checks.

2021-03-19 02:31 UTC, talanknight commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
> +func (s Service) ChangeState(ctx context.Context, req *pbs.ChangeStateRequest) (*pbs.ChangeStateResponse, error) {
I've added nil checks in all validate* methods.

2021-03-19 02:31 UTC, talanknight commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
> +	am, err := s.changeStateInRepo(ctx, req.GetId(), req.GetState(), req.GetVersion())
Done.

2021-03-19 02:31 UTC, talanknight commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
> +	if err := populateCollectionAuthorizedActions(ctx, authResults, am); err != nil {
Happy to chat.  This is just to populate the authorized actions on the resource returned.

2021-03-19 02:31 UTC, talanknight commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
>  func (s Service) createPwInRepo(ctx context.Context, scopeId string, item *pb.AuthMethod) (*password.AuthMethod, error) {
I've added nil checks in all validate* methods.

2021-03-19 02:31 UTC, talanknight commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
>  func (s Service) createOidcInRepo(ctx context.Context, scopeId string, item *pb.AuthMethod) (*oidc.AuthMethod, error) {
I've added nil checks in all validate* methods which is done prior to this call.

2021-03-19 02:31 UTC, talanknight commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
> +func (s Service) updateOidcInRepo(ctx context.Context, scopeId, id string, mask []string, item *pb.AuthMethod) (*oidc.AuthMethod, error) {
I've added nil checks in all validate* methods.

2021-03-19 02:31 UTC, talanknight commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
> +	repo, err := s.oidcRepoFn()
All invalid parameter checks is done in validateStateRequest which is performed prior to this method being called.

2021-03-19 02:31 UTC, talanknight commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
> +func toStoragePwAuthMethod(scopeId string, item *pb.AuthMethod) (*password.AuthMethod, error) {
I've added nil checks in all validate* methods.

2021-03-19 02:31 UTC, talanknight commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
>  				badFields["type"] = "Cannot modify the resource type."
Extracted field names into consts as you suggested.

2021-03-19 02:31 UTC, talanknight commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
> +				badFields["attributes.client_id"] = "Can change but cannot unset this field."
I've changed them to make sure they are aligned.

2021-03-19 02:31 UTC, talanknight commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
> +func validateChangeStateRequest(req *pbs.ChangeStateRequest) error {
I've added nil checks in all validate* methods.

2021-03-19 02:31 UTC, talanknight commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
> +		badFields["version"] = "Resource version is required."
Made the field names consts.

2021-03-19 02:31 UTC, talanknight commented on internal/types/action/action.go
> +	ChangeState      Type = 33
Woops, I missed the action.Map and action string method Thanks for catching that.

2021-03-19 15:00 UTC, jimlambrt commented
Looks like there are some failing tests.

2021-03-19 21:07 UTC, talanknight commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
> +	switch state {
I've added one.  This is something that should have been caught in validateChangeStateRequest however.

2021-03-19 21:46 UTC, talanknight commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
> +	case stateInactive, statePrivate, statePublic:
Made the states an email.  ty!

2021-03-19 21:46 UTC, talanknight commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
> +	stateInactive = "inactive"
made the states an enum, ty!

2021-03-19 22:30 UTC, talanknight commented on internal/proto/local/controller/api/resources/authmethods/v1/auth_method.proto
> +	repeated string audiences = 110 [json_name="audiences", (custom_options.v1.mask_mapping) = {this:"attributes.audiences" that: "AudClaims"}];
Renamed "allowed_audiences"

2021-03-19 22:30 UTC, talanknight commented on internal/proto/local/controller/storage/auth/oidc/store/v1/oidc.proto
> +  repeated string aud_claims = 180 [(custom_options.v1.mask_mapping) = {this:"AudClaims" that:"attributes.audiences"}];
Renamed "allowed_audiences"

2021-03-21 13:13 UTC, jimlambrt commented on internal/proto/local/controller/storage/auth/password/store/v1/password.proto
> +  string name = 4 [(custom_options.v1.mask_mapping) = {this:"Name" that: "name"}];
BTW, pw auth method also calls BuildUpdatePaths(...) a few lines further down from the line you referenced:
https://github.com/hashicorp/boundary/blob/5162cc4570dfe19a74a4aa4f5f09f54b2225a595/internal/auth/password/repository_authmethod.go#L215

With all that said, I think common.BuildUpdatePaths(...) is intended to be used for "all" updates, so it sort of sets the standard... but I'm not advocating some big refactor here.  Perhaps we need a backlog issue to make off of this consistent so it follows one pattern?

2021-03-21 13:15 UTC, jimlambrt commented on internal/proto/local/controller/storage/auth/oidc/store/v1/oidc.proto
> +  repeated string aud_claims = 180 [(custom_options.v1.mask_mapping) = {this:"AudClaims" that:"attributes.audiences"}];
ty!

2021-03-21 13:38 UTC, jimlambrt commented on internal/types/action/action.go
> +	ChangeState      Type = 33
I think, you might need to still add a test for ChangeState in `TestAction(...)`

2021-03-21 13:43 UTC, jimlambrt commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
> +func (s Service) ChangeState(ctx context.Context, req *pbs.ChangeStateRequest) (*pbs.ChangeStateResponse, error) {
ty!

2021-03-21 13:43 UTC, jimlambrt commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
> +	if err := populateCollectionAuthorizedActions(ctx, authResults, am); err != nil {
ah.

2021-03-21 13:47 UTC, jimlambrt commented on internal/servers/controller/handlers/authmethods/authmethod_service.go
> +				badFields["attributes.callback_urls"] = "Field is read only."
I think, it's fine given that it's changing anywho.  ty for clarifying.

2021-03-21 13:52 UTC, jimlambrt approved these changes
No need for me to re-review after you add the one missing test.  Nice work!

2021-03-22 17:35 UTC, merged