Add membership setting function
hashicorp/boundary pull request #1259
Opened 2021-05-28 15:47 UTC by jefferai

This adds the function that, given a list of managed groups and an account, handles updating memberships.

2021-05-29 18:24 UTC, jimlambrt requested changes
Great work and the tests are really well done.  Just a few minor cut/paste bits.

2021-05-29 18:24 UTC, jimlambrt commented on internal/auth/oidc/repository_managed_group_members.go
> +// group's version as this is used to ensure consistency.
Perhaps add: "it's understood that managed groups are eventually consistent and that these msgs represent the point in time we will consist the msgs to."

2021-05-29 18:24 UTC, jimlambrt commented on internal/auth/oidc/repository_managed_group_members.go
> +				return errors.Wrap(err, op, errors.WithMsg("unable to retrieve current principal roles after sets"))
need to update WithMsg(...)

2021-05-29 18:24 UTC, jimlambrt commented on internal/auth/oidc/repository_managed_group_members.go
> +				return errors.Wrap(err, op, errors.WithMsg("unable to retrieve current principal roles after sets"))
need to update this WithMsg as well.

2021-05-29 18:24 UTC, jimlambrt commented on internal/auth/oidc/repository_managed_group_members_test.go
> +	// Note: using a test controller here for ease of setup as we need a working
ty for the comment!

2021-05-29 18:24 UTC, jimlambrt commented on internal/auth/oidc/repository_managed_group_members_test.go
> +	rows, err := rw.Query(ctx, "select public_id from auth_oidc_account limit 2", nil)
you could refactor this to just use vanilla db.SearchWhere(...) WithLimit(2) and an []Account

2021-05-29 18:24 UTC, jimlambrt commented on internal/auth/oidc/repository_managed_group_members_test.go
> +	// This test can be run in parallel; the subtests *cannot*.
ty for the comment!

2021-06-01 00:42 UTC, jefferai commented
@jimlambrt I've addressed all feedback in 61637ca

2021-06-01 16:50 UTC, jimlambrt approved these changes

2021-06-01 18:52 UTC, vancluever approved these changes
LGTM, again, mainly informational for me, but also again great context for my understanding of the codebase 🙂

2021-06-01 19:18 UTC, merged