Vault job credential and credential store cleanup
hashicorp/boundary pull request #1331
Opened 2021-06-17 21:08 UTC by louisruch

### What does this PR do

- Allows library_id and session_id to be null on a credential
- On delete set null on both library_id and session_id instead of cascade
- Adds a trigger to set status to revoke when moving to null session_id
- Adds job to delete cred stores that are soft deleted and have no active tokens
- Adds job to delete credentials that have been soft deleted and are not active

2021-06-17 21:08 UTC, louisruch commented
@mgaffney PTAL

2021-06-18 17:24 UTC, mgaffney commented on internal/credential/vault/jobs_test.go
> +	require.NotNil(token)
Hopefully #1332 can help with this

2021-06-18 19:12 UTC, louisruch commented on internal/credential/vault/jobs_test.go
> +	require.NotNil(token)
This was perfect!

2021-06-18 19:30 UTC, mgaffney requested changes
This looks great! Just needs one thing.

2021-06-18 19:30 UTC, mgaffney commented on internal/db/schema/migrations/postgres/12/03_vault_credential.up.sql
> +  create function not_null_columns()
Can you add a test to `internal/db/domains_test.go` for this?

2021-06-18 20:06 UTC, mgaffney approved these changes
Looks great!

2021-06-18 21:29 UTC, merged