Add session cleanup changes to CHANGELOG.md
hashicorp/boundary pull request #1426
Opened 2021-07-28 22:50 UTC by vancluever

This adds the changelog entries associated with the following PRs:

#1340 
#1354
#1400
#1410

2021-07-29 21:48 UTC, jefferai submitted a review, later dismissed
Looks good. One comment: in the first bullet point, the last sentence could be seen to mean that workers won't close connections _until_ the status update comes after connectivity is restored. Might be better to instead note that it will be cleaned up at that point, but will have already been closed.

2021-07-29 22:40 UTC, vancluever commented
I think I'm just going to strike that part as I think the extra context can be confusing, I can't seem to find a good way to explain it more without writing a book. 😜 I think just saying that the controller is now marking the connections closed like the worker does should be good enough.

2021-07-30 01:03 UTC, jimlambrt requested changes
one small suggestion

2021-07-30 01:03 UTC, jimlambrt commented on CHANGELOG.md
> +  worker, this timeout for this behavior is 15s.
```suggestion
  worker, the timeout for this behavior is 15s.
```

2021-07-30 01:05 UTC, jimlambrt approved these changes

2021-07-30 15:55 UTC, merged