Add plugin details to host catalog, host set, and host domain model pages
hashicorp/boundary pull request #1715
Opened 2021-11-16 21:35 UTC by talanknight

2021-11-16 23:42 UTC, mgaffney requested changes
Can remove the formatting only changes or split them into a different commit?

2021-11-16 23:50 UTC, mgaffney submitted a review, later dismissed

2021-11-17 00:10 UTC, sswati0 approved these changes

2021-11-17 20:53 UTC, mgaffney approved these changes
I left some minor suggestions.

2021-11-17 20:53 UTC, mgaffney commented on website/content/docs/concepts/domain-model/host-catalogs.mdx
> +  service. The set of fields which should be included in this attributes.
```
The set of fields which should be included in this attributes.
```
This sentence doesn't make sense to me.

2021-11-17 20:53 UTC, mgaffney commented on website/content/docs/concepts/domain-model/host-sets.mdx
> +  or `dns:<globbed name>` used to select the addresses of a [hosts][] when
```suggestion
  or `dns:<globbed name>` used to select the addresses of [hosts][] when
```

2021-11-17 21:07 UTC, mgaffney approved these changes

2021-11-17 21:11 UTC, merged