Create the network address dimension
hashicorp/boundary pull request #1775
Opened 2021-12-08 18:02 UTC by talanknight

This also migrates existing addresses into the new dimension.

2021-12-08 20:19 UTC, tmessi requested changes

2021-12-08 20:19 UTC, tmessi commented on internal/db/schema/migrations/oss/postgres/22/02_wh_network_address_dimensions.up.sql
> +  create function wh_try_cast_inet(text)
can you add some [sqltests](https://github.com/hashicorp/boundary/blob/main/internal/db/sqltest/README.md) for this function?

2021-12-08 20:19 UTC, tmessi commented on internal/db/schema/migrations/oss/postgres/22/02_wh_network_address_dimensions.up.sql
> +  create function wh_private_address_status(inet) returns text
can you add some [sqltests](https://github.com/hashicorp/boundary/blob/main/internal/db/sqltest/README.md) for this function?

2021-12-08 20:19 UTC, tmessi commented on internal/db/schema/migrations/oss/postgres/22/02_wh_network_address_dimensions.up.sql
> +    'None',
Should `dns_name` be `None` here? I would think it should be `Not Applicable`

2021-12-08 20:31 UTC, talanknight commented
FYI, I am trying to break this WH work up into smaller PRs so we can have more targets conversations but I decided after creating this PR that where I stopped was probably not a good stopping point.  I added checklists to the description of this PR and plan on adding those before I send it out for review again.

Sorry for the noise, and I'm also happy to discuss what's already here if that would be valuable.

2021-12-09 20:10 UTC, talanknight commented
This PR overly focused on the migration of old data to new tables aspect.  I'm going to close this PR and change my approach to consider the capturing of live data first and then, only after all that is resolved, work out the migration of old data.

2021-12-09 20:10 UTC, closed without merging