Migrate host address from the host dimension table to host address dimension table
hashicorp/boundary pull request #1827
Opened 2022-01-21 20:33 UTC by talanknight

2022-01-27 12:16 UTC, tmessi requested changes
looks good. I just have some minor style related suggestions

2022-01-28 20:26 UTC, talanknight commented on internal/db/schema/migrations/oss/postgres/25/01_wh_network_address_dimensions.up.sql
> +  on conflict do nothing;
Done.  Thank you!

2022-01-31 15:16 UTC, tmessi commented on internal/db/schema/migrations/oss/postgres/25/01_wh_network_address_dimensions.up.sql
> +  on conflict do nothing;
You changed this for `wh_network_address_group_membership` but not for the inserts into `wh_network_address_group`

2022-01-31 18:13 UTC, talanknight commented on internal/db/schema/migrations/oss/postgres/25/01_wh_network_address_dimensions.up.sql
> +  on conflict do nothing;
Woops.  Fixed now.

2022-02-02 15:01 UTC, tmessi approved these changes

2022-02-02 17:15 UTC, irenarindos reviewed
Just wanted to comment that you'll need to move your migrations to 26- a PR went in yesterday under 25: https://github.com/hashicorp/boundary/tree/main/internal/db/schema/migrations/oss/postgres/25

2022-02-07 15:51 UTC, mgaffney approved these changes

2022-02-07 17:43 UTC, merged