refactor(plugin): convert grpc error codes into Boundary error codes
hashicorp/boundary pull request #1916
Opened 2022-03-12 00:35 UTC by A-440Hz

2022-03-14 15:35 UTC, talanknight requested changes
This looks like it is moving our errors for plugins in a good direction.

Could you also provide in the PR a before/after example of what aws/azure invalid arguments error looks like?  This can show us what state we have arrived at in terms of readability of the errors and help us evaluate if we should continue or pause on our path towards more readable errors for plugins.

2022-03-14 15:35 UTC, talanknight commented on internal/errors/code.go
> +	PluginAborted            Code = 5002 // PluginAborted represents a plugin error where a non-native library call was not able to run to completion
Could you clarify that these are not errors with the plugin system itself but errors that the plugins report back?  To me just saying "a plugin error" leaves that bit ambiguous.

2022-03-14 15:35 UTC, talanknight commented on internal/host/plugin/repository_host_catalog.go
> +					switch {
Can you add tests to verify these behave as expected?  For the changes in this file and the repository_host_set file.

2026-09-17 14:47 UTC, irenarindos commented
Closing as old

2026-09-17 14:47 UTC, closed without merging