feat(groups): Classify resources for audit events
hashicorp/boundary pull request #1987
Opened 2022-04-08 17:39 UTC by tmessi

2022-04-08 18:14 UTC, johanbrandhorst approved these changes

2022-04-12 19:14 UTC, jefferai commented on internal/proto/controller/api/services/v1/group_service.proto
> +  string id = 1; // @gotags: `class:"public"`
Same comments in here about tags on messages

2022-04-12 19:19 UTC, jefferai requested changes
Same comment here about tagging the messages

2022-04-14 19:27 UTC, jimlambrt approved these changes

2022-04-14 22:32 UTC, jefferai approved these changes

2022-04-15 11:37 UTC, merged