Add worker config table and view
hashicorp/boundary pull request #2090
Opened 2022-05-19 23:55 UTC by talanknight

Also the worker domain object contains a WorkerConfig object as well as methods for CanonicalAddress and LastConnectionUpdate which returns values based on a combination of worker and config values.

A new view has been added to get all tags and the config along with the worker in a single db query.

Target service has been refactored to use some of the new functions listed above and to try to make the worker filtering logic easier to follow.

2022-05-20 12:57 UTC, irenarindos commented on internal/proto/controller/storage/servers/store/v1/worker.proto
> +  // @inject_tag: `gorm:"primary_key"`
I think the primary_key tag needs to also be added on key and value to represent the composite primary key for worker tags

2022-05-20 12:57 UTC, irenarindos commented on internal/session/query.go
> +           from server_worker_config
Do we need to detect "dead" workers that don't have a config?

2022-05-23 12:50 UTC, irenarindos commented on internal/servers/worker_status.go
> +// TableName overrides the table name used by WorkerStatus to `server_worker_config`
```suggestion
// TableName overrides the table name used by WorkerStatus to `server_worker_status`
```

2022-05-23 12:50 UTC, irenarindos commented on internal/servers/worker.go
> +func tagsFromAggregatedTagString(ctx context.Context, s string) ([]*Tag, error) {
Wondering if this function should be documented to explain the delimiters/ parsing.

2022-05-23 17:25 UTC, irenarindos approved these changes

2022-05-24 13:10 UTC, jimlambrt requested changes
a few minor bits.  great work!

2022-05-24 13:10 UTC, jimlambrt commented on internal/daemon/controller/handlers/targets/target_service_test.go
> +
any chance you'd take a stab at implementing a basic unit test for `AuthorizeSession(...)`?

2022-05-24 17:34 UTC, jimlambrt commented on internal/servers/repository_worker.go
>  	if liveness > 0 {
ty

2022-05-24 17:34 UTC, jimlambrt commented on internal/servers/repository_worker.go
>  // listWorkersWithReader will return a listing of resources and honor the WithLimit option or the repo
ty

2022-05-24 17:40 UTC, jimlambrt commented on internal/daemon/controller/handlers/targets/target_service_test.go
> +
ty!

2022-05-24 17:44 UTC, jimlambrt approved these changes

2022-05-24 18:42 UTC, mgaffney commented on internal/db/schema/migrations/oss/postgres/99/02_worker_controller_tables.up.sql
> +  name wt_name
What value is in the `name` column?

2022-05-24 20:05 UTC, jefferai commented on internal/session/query.go
> +         select
The most minor of nits: you have a mix of spaces/tabs in this query

2022-05-24 20:06 UTC, jefferai approved these changes

2022-05-24 22:08 UTC, merged