Add the Read/List service functions
hashicorp/boundary pull request #2123
Opened 2022-06-02 17:08 UTC by talanknight

Additionally I have set up the handler registration for the worker service so requests can be sent the the `/v1/workers` path.

2022-06-02 18:48 UTC, irenarindos requested changes

2022-06-02 18:48 UTC, irenarindos commented on internal/proto/controller/api/resources/workers/v1/worker.proto
> -  string version = 30;
Don't we still need version?

2022-06-03 01:02 UTC, A-440Hz commented on internal/servers/testing.go
> +	namePart, err := newWorkerId(context.Background())
why is this context different from the one used for `UpdateWorker` at the end?

2022-06-03 12:40 UTC, irenarindos commented on internal/daemon/controller/handlers/workers/worker_service_test.go
> +			name: "Filter to a 2 workers",
```suggestion
			name: "Filter to 2 workers",
```

2022-06-03 12:41 UTC, irenarindos commented on internal/proto/controller/api/resources/workers/v1/worker.proto
> -  string version = 30;
Does the version field on the workerAggregate need to be removed as well?

2022-06-03 15:25 UTC, irenarindos approved these changes

2022-06-03 18:19 UTC, merged