Hz initial upstreams
hashicorp/boundary pull request #2151
Opened 2022-06-08 06:26 UTC by A-440Hz

refact(worker): rename 'controllers' address field in worker config to 'initial_upstreams'

2022-06-08 13:47 UTC, irenarindos requested changes

2022-06-08 13:47 UTC, irenarindos commented on internal/daemon/worker/auth_rotation_test.go
> -		InitialControllers: c.ClusterAddrs(),
There are a several tests failing because they reference InitialControllers; can they be updated to InitialUpstreams?

2022-06-09 01:09 UTC, jefferai commented
I'll get back to reviewing this later (which will also give some time to make the requested changes).

Can you also update the documentation in the website folder to describe `initial_upstreams` instead of `controllers` for the worker documentation?

2022-06-10 18:33 UTC, A-440Hz commented
I an not sure why I keep failing the worker shutdown reload test. At first I thought it was because my changes with loading both "controllers" and "initial_upstreams" workers slower slower to reload, but it doesn't make sense given the worker config in that test. In any case I'm fairly sure this test is failing not only because it is flaky, but because of some change I made to the workers.

2022-06-10 22:04 UTC, A-440Hz commented on internal/cmd/config/config.go
> +// Decodes and returns the ControllersRaw interface if both it and InitialUpstreams are populated so we can compare with InitialUpstreams once decoded
Yeah I think this makes sense. It seems contrived to allow them to populate both, only if they are the same value

2022-06-10 22:04 UTC, A-440Hz commented on internal/cmd/config/config.go
> +func stringSlicesEqual(a, b []string) bool {
noted. thanks!

2022-06-10 22:05 UTC, A-440Hz commented on internal/cmd/config/config.go
> +	InitialUpstreams interface{} `hcl:"initial_upstreams"`
RawUpstreams for line 186 and InitialUpstreams for the processed var on 185?

2022-06-10 22:11 UTC, A-440Hz commented on internal/cmd/commands/database/init.go
> +	if c.Config.Worker.ControllersRaw != nil {
Is there another file where you think this check would be better?

2022-06-10 22:16 UTC, jefferai commented on internal/cmd/config/config.go
> +func stringSlicesEqual(a, b []string) bool {
Or, if you don't care about ordering, use https://github.com/hashicorp/go-secure-stdlib/blob/main/strutil/strutil.go#L295

2022-06-10 22:17 UTC, jefferai commented on internal/cmd/config/config.go
> +func stringSlicesEqual(a, b []string) bool {
(Better link: https://pkg.go.dev/github.com/hashicorp/go-secure-stdlib/strutil#EquivalentSlices)

2022-06-10 22:19 UTC, jefferai commented on internal/cmd/config/config.go
> +	InitialUpstreams interface{} `hcl:"initial_upstreams"`
`InitialUpstreamsRaw` for the `interface{}`, `InitialUpstreams` for the parsed version. BTW, we're on Go 1.18, feel free to use `any` instead :-D

2022-06-10 22:20 UTC, jefferai commented on internal/cmd/config/config.go
> +		w.InitialUpstreams = w.ControllersRaw
![image](https://user-images.githubusercontent.com/28627/173157948-df2a203f-3ee1-4a8e-8958-02fc40575011.png)

2022-06-13 22:06 UTC, merged