Ddebko ICU-2122 Enforce Typed Definitions In API Module
hashicorp/boundary pull request #2238
Opened 2022-06-28 16:36 UTC by ddebko

[Issue-2122](https://github.com/hashicorp/boundary/issues/2122)

## Summary:

The focus for issue 2122 is to add typed definitions to our return methods in the API module. Currently we are returning generic types (interface{}), which requires the user to type cast the value into the expected typed definition. Otherwise, the values stored in the generic type are hidden. This PR adds the typed definitions to the API module by updating the template in the genapi package. The changes to the API module created a cascading error effect in the cli commands, which is why I listed many items in the changes section for the cli module.

## Changes:
- Updated apigen module template
  - Changed return type for ReadResult.GetItem() from interface{} to typed definition
  - Changed return type for ListResult.GetItems() from interface{} to typed definition
  - Delete interface definitions: GenericResult, GenericDeleteResult, GenericListResult
- Updated cligen module template
  - removed references to typed interface definitions: GenericResult, GenericDeleteResult, GenericListResult
  - added typed references
    - *api.Response
    - *{{ .PackageName }}.{{ Resource Type }}                       
      - Ex.) *authtokens.AuthToken
    - []*{{ .PackageName }}.{{ Resource Type }}                     
      - Ex.) []*authtokens.AuthToken
    - *{{ .PackageName }}.{{ Resource Type }}ReadResult
      - Ex.) *authtokens.AuthTokenReadResult    
    - *{{ .PackageName }}.{{ Resource Type }}DeleteResult 
      - Ex.) *authtokens.AuthTokenDeleteResult
    - *{{ .PackageName }}.{{ Resource Type }}ListResult
      - Ex.) *authtokens.AuthTokenListResult
  - updated cli helper func executeExtraActions
    - removed parameter "origResult api.GenericResult"
    - added parameters/return types:
      - origResp *api.Response
      - origItem  *{{ .PackageName }}.{{ Resource Type }}
      - origItems []*{{ .PackageName }}.{{ Resource Type }}
        - note this is only generated when a command has a Result type with a method GetItems()
  - updated cli helper funcs PrintJsonItem & PrintJsonItems to pass in *api.Response in format.go
  - updated all helper funcs in files labels funcs.go in gencli package
    - updated executeExtraActionsImpl to match func definition in generated files
    - fixed printItemTable by a case to case situation depending on the command

## Concerns:
- In the API module we have a DeleteResult type that always returns a nil value for GetItem and we have a comment for the functions to explain this, therefore I decided not to change the return type.
- This is a breaking change for users that are currently using the API Module

2022-06-28 18:42 UTC, johanbrandhorst requested changes
This looks really good. Could you also prepare some notes in the CHANGELOG that detail the exact breaking changes for an external user of the `api` module?

2022-06-28 18:42 UTC, johanbrandhorst commented on internal/cmd/gencli/templates.go
> +
Nit: do we need these lines?

2022-06-28 18:42 UTC, johanbrandhorst commented on internal/tests/cluster/recursive_anon_listing_test.go
> -	require.Len(l.GetItems().([]*amapi.AuthMethod), 3)
:chefs_kiss:

2022-06-28 22:41 UTC, ddebko commented on internal/tests/cluster/recursive_anon_listing_test.go
> -	require.Len(l.GetItems().([]*amapi.AuthMethod), 3)
thank you

2022-06-28 22:41 UTC, ddebko commented on internal/cmd/gencli/templates.go
> +
Good catch, I will delete these lines.

2022-07-05 13:53 UTC, tmessi approved these changes

2022-07-06 17:08 UTC, johanbrandhorst requested changes
Please rebase this on the v0.9.1 release changelog changes

2022-07-13 17:22 UTC, johanbrandhorst submitted a review, later dismissed
LGTM but wait for Louis and Mike

2022-07-18 05:28 UTC, louisruch approved these changes
:shipit:

2022-07-21 22:11 UTC, johanbrandhorst approved these changes

2022-07-21 22:21 UTC, merged