Boundary documentation: content cleanup in prep for devdot migration
hashicorp/boundary pull request #2249
Opened 2022-07-08 22:37 UTC by taoism4504

In preparation to migrate boundary docs to devdot in August, I'm taking the liberty to do perform some content cleanup before the migration.

:mag: [Deploy Preview]()

2022-07-08 22:47 UTC, yhyakuna approved these changes
LGTM

2022-07-12 18:06 UTC, stellarsquall requested changes
looking great! 

only two real comments, one on using direct tutorial links instead of including the collection context, the other was a question about style guide bits.

2022-07-12 18:06 UTC, stellarsquall commented on website/content/docs/concepts/domain-model/groups.mdx
> +Refer to the [Manage Users and Groups with HCP Boundary](https://learn.hashicorp.com/tutorials/boundary/hcp-manage-users-groups?in=boundary/hcp-administration) tutorial to learn how to complete user
for all tutorial links, I like to remove the collection URL in order to ensure the tutorial can be found if it's moved to another collection, or if a redirect is created. I suffered this recently 

```suggestion

## Tutorial

Refer to the [Manage Users and Groups with HCP Boundary](https://learn.hashicorp.com/tutorials/boundary/hcp-manage-users-groups) tutorial to learn how to complete user management related tasks.
```
```suggestion

## Tutorial

Refer to the [Manage Users and Groups with HCP Boundary](https://learn.hashicorp.com/tutorials/boundary/hcp-manage-users-groups?in=boundary/hcp-administration) tutorial to learn how to complete user managemement related tasks.
```

2022-07-12 18:06 UTC, stellarsquall commented on website/content/docs/concepts/domain-model/roles.mdx
> +Refer to the [Managed Roles and Permissions with HCP Boundary](https://learn.hashicorp.com/tutorials/boundary/hcp-manage-roles?in=boundary/hcp-administration) tutorial to learn how to create a role i
```suggestion
Refer to the [Managed Roles and Permissions with HCP Boundary](https://learn.hashicorp.com/tutorials/boundary/hcp-manage-roles) tutorial to learn how to create a role in Boundary.
```
```suggestion
Refer to the [Managed Roles and Permissions with HCP Boundary](https://learn.hashicorp.com/tutorials/boundary/hcp-manage-roles?in=boundary/hcp-administration) tutorial to learn how to create a role in Boundary.
```

2022-07-12 18:06 UTC, stellarsquall commented on website/content/docs/concepts/domain-model/scopes.mdx
> +Refer to the [Manage Scopes with HCP Boundary](https://learn.hashicorp.com/tutorials/boundary/hcp-manage-scopes?in=boundary/hcp-administration) tutorial to learn how to create an org scope and a proj
```suggestion
Refer to the [Manage Scopes with HCP Boundary](https://learn.hashicorp.com/tutorials/boundary/hcp-manage-scopes) tutorial to learn how to create an org scope and a project scope.
```
```suggestion
Refer to the [Manage Scopes with HCP Boundary](https://learn.hashicorp.com/tutorials/boundary/hcp-manage-scopes?in=boundary/hcp-administration) tutorial to learn how to create an org scope and a project scope.
```

2022-07-12 18:06 UTC, stellarsquall commented on website/content/docs/concepts/domain-model/sessions.mdx
> +Refer to the[] Manage Sessions with HCP Boundary](https://learn.hashicorp.com/tutorials/boundary/hcp-manage-sessions?in=boundary/hcp-administration) tutorial to learn how to start, view, and cancel a
```suggestion
Refer to the[] Manage Sessions with HCP Boundary](https://learn.hashicorp.com/tutorials/boundary/hcp-manage-sessions) tutorial to learn how to start, view, and cancel a session.
```
```suggestion
Refer to the[] Manage Sessions with HCP Boundary](https://learn.hashicorp.com/tutorials/boundary/hcp-manage-sessions?in=boundary/hcp-administration) tutorial to learn how to start, view, and cancel a session.
```

2022-07-12 18:06 UTC, stellarsquall commented on website/content/docs/configuration/worker/pki-worker.mdx
> +Refer to the [Self-Managed Worker Registration with HCP Boundary](https://learn.hashicorp.com/tutorials/boundary/hcp-manage-workers?in=boundary/hcp-administration) tutorial to learn how to register a
```suggestion
Refer to the [Self-Managed Worker Registration with HCP Boundary](https://learn.hashicorp.com/tutorials/boundary/hcp-manage-workers) tutorial to learn how to register and manage PKI workers.
```
```suggestion
Refer to the [Self-Managed Worker Registration with HCP Boundary](https://learn.hashicorp.com/tutorials/boundary/hcp-manage-workers?in=boundary/hcp-administration) tutorial to learn how to register and manage PKI workers.
```

2022-07-12 18:06 UTC, stellarsquall commented on website/content/docs/getting-started/deploy-and-login.mdx
> +- Refer to the [Install Boundary Desktop](https://learn.hashicorp.com/tutorials/boundary/hcp-getting-started-desktop-app?in=boundary/hcp-getting-started) tutorial to learn how to use the Boundary des
```suggestion
- Refer to the [Create a Boundary Instance on HCP](https://learn.hashicorp.com/tutorials/boundary/hcp-getting-started-create) tutorial to learn how to deploy a Boundary instance.
- Refer to the [Install Boundary Desktop](https://learn.hashicorp.com/tutorials/boundary/hcp-getting-started-desktop-app) tutorial to learn how to use the Boundary desktop to connect to a running HCP Boundary instance.
```
```suggestion

2022-07-12 19:28 UTC, stellarsquall approved these changes
great work!

2022-07-12 19:29 UTC, merged