Upgrade to Go 1.19
hashicorp/boundary pull request #2347
Opened 2022-08-10 22:15 UTC by johanbrandhorst

Go 1.19 includes new behavior for `go fmt` and other tools that depend on its behavior (like `goimports` and `gofumpt`).

2022-08-11 01:25 UTC, louisruch requested changes
Found a couple places where it seems someone was putting comments on a newline and included a leading space. Other than that is this great thanks!

2022-08-11 01:25 UTC, louisruch commented on internal/auth/oidc/repository_auth_method_read.go
> -//  all other options are ignored.
The extra space here was an error

2022-08-11 01:25 UTC, louisruch commented on internal/daemon/controller/handlers/filtering.go
> -//   values in the request or the request context itself.
same re extra space triggering a list

2022-08-11 01:25 UTC, louisruch commented on internal/db/schema/internal/postgres/postgres.go
> -//  The WithDeleteLog option is supported and will remove all log entries,
space

2022-08-11 01:25 UTC, louisruch commented on internal/db/schema/migration_log.go
> -//  The WithDeleteLog option is supported and will remove all log entries when provided.
space

2022-08-11 13:22 UTC, jefferai commented
I suspect the author of some comment wrapping plugin is going to get a strongly worded tweet :-)

2022-08-11 18:35 UTC, johanbrandhorst commented
I've fixed the whitespace errors (and a few new ones), please take another look!

2022-08-18 18:05 UTC, louisruch approved these changes
LGTM

2022-08-25 16:12 UTC, merged