Add vault test to e2e test suite
hashicorp/boundary pull request #2474
Opened 2022-09-19 22:52 UTC by moduli

This PR adds tests that use Vault as a credential store. A new enos scenario was created to spin up a vault instance alongside a boundary cluster. The test then sets up Vault as a credential store, creates a set of credentials, and attaches those credentials to a target.

As a design philosophy, we wanted to minimize the amount of setup done in enos in order to maintain as much flexibility as possible with regards to how the infrastructure gets created. 

Some additional refactoring was done to create methods for commonly used boundary operations.

```
❯ enos scenario run e2e_vault builder:local
Scenario: e2e_vault [builder:local]
  Generate: ✅
  Init: ✅
  Validate: ✅
  Plan: ✅
  Apply: ✅
  Destroy: ✅
```
```
❯ go test -v github.com/hashicorp/boundary/testing/internal/e2e/vault
=== RUN   TestCreateVaultCredentialStoreCli
    vault_test.go:83: Using Vault Address: http://44.204.115.92:8200
    vault_test.go:123: Created Vault Credential
    vault_test.go:142: Created Vault Cred Store Token: {TOKEN}
    vault_test.go:155: Created Org Id: o_hCrwhLCZHp
    vault_test.go:160: Created Project Id: p_Ahwlt8eiki
    vault_test.go:176: Created Credential Store: csvlt_yKth9KCIHp
    vault_test.go:192: Created Credential Library: clvlt_GLuKKgDFhM
    vault_test.go:206: Created Host Catalog: hcst_ezcv0DZgCM
    vault_test.go:220: Created Host Set: hsst_Hi7NnHWnBQ
    vault_test.go:235: Created Host: hst_a3vSteyXw8
    vault_test.go:258: Created Target: ttcp_uuUkPwd9et
    vault_test.go:293: Successfully retrieved credentials for target
--- PASS: TestCreateVaultCredentialStoreCli (4.32s)
=== RUN   TestCreateVaultCredentialStoreApi
--- PASS: TestCreateVaultCredentialStoreApi (0.00s)
PASS
ok  	github.com/hashicorp/boundary/testing/internal/e2e/vault	4.514s
```

2022-09-20 16:21 UTC, moduli commented on testing/internal/e2e/vault/vault.go
> +	output := e2e.RunCommand(
I'm changing this to use `vault policy list` here and moving the `policy write` into the test

2022-09-22 20:30 UTC, moduli commented on testing/internal/e2e/target/target_test.go
> +		targets.WithTcpTargetDefaultPort(uint32(targetPort)),
Not sure this was the right way to convert this string to an int

2022-09-23 02:59 UTC, moduli commented on enos/enos-scenario-e2e-vault.hcl
> +  step "create_vault_cluster" {
This file the same as the target scenario except for the addition of this step and passing the respective info to the e2e test

2022-09-23 16:20 UTC, joshbrand commented on enos/modules/test_e2e/main.tf
> +module "ensure_jq" {
should this go in enos-modules?

2022-09-26 14:00 UTC, tmessi requested changes
Can you add something to the [e2e REAMDE](https://github.com/hashicorp/boundary/blob/moduli-e2e-test-vault/testing/internal/e2e/README.md#local) to note the need for some vault env vars, specifically `VALUT_ADDR` and `VAULT_TOKEN`, along with the need to run a vault instance?.

2022-09-26 14:59 UTC, moduli commented on testing/internal/e2e/credential/vault/vault_test.go
> +	secretPath := "secret"
👍 I can also change this to be e2e specific so that it won't clash

2022-09-26 20:10 UTC, tmessi approved these changes

2022-09-27 17:23 UTC, merged