Add interfaces and error codes for processing downstream router connections
hashicorp/boundary pull request #2511
Opened 2022-10-03 16:28 UTC by talanknight

2022-10-03 23:01 UTC, johanbrandhorst requested changes

2022-10-03 23:01 UTC, johanbrandhorst commented on internal/daemon/controller/controller.go
> +	// incoming client connections and processes them. This never returns until
Nit: this reads a bit weird 😁.
```suggestion

	// ProcessPendingConnections starts a function that continually processes
	// incoming client connections. This never returns until
```

2022-10-03 23:01 UTC, johanbrandhorst commented on internal/daemon/worker/worker.go
> +	// incoming client connections and processes them. This never returns until
```suggestion
	// ProcessPendingConnections starts a function that continually processes
	// incoming client connections. This never returns until
```

2022-10-03 23:01 UTC, johanbrandhorst commented on internal/errors/code.go
> +	QueueIsFull                        = 125 // QueueIsFull results in attempting to add an item to a queue which is full
Where are these used?

2022-10-03 23:37 UTC, johanbrandhorst commented on internal/errors/code.go
> +	QueueIsFull                        = 125 // QueueIsFull results in attempting to add an item to a queue which is full
Could we add a comment? I think I see the practical reason for putting this here but it might still be confusing to see unused constants.

2022-10-04 12:18 UTC, irenarindos approved these changes

2022-10-04 18:07 UTC, merged