Docs deploy and login updates
hashicorp/boundary pull request #2574
Opened 2022-10-26 21:41 UTC by stellarsquall

This PR updates the `/docs/getting-started/connect-to-target` page:

- fixes h1 header issue
- replaces Origin URL with Cluster URL
- removes references to Beta
- removes content duplicated in the dev-portal page sub-heading
- fixes various code snippet styles

2022-10-27 14:15 UTC, xingluw approved these changes
LGTM

2022-10-28 15:40 UTC, ashleemboyer requested changes
Just one comment! 😊

2022-10-28 15:40 UTC, ashleemboyer commented on website/content/docs/getting-started/deploy-and-login.mdx
> +## Deploy HCP Boundary and Login
Since this is the page title, we'll need it to be an `<h1>` element instead of an `<h2>`.

```suggestion
# Deploy HCP Boundary and Login
```

2022-10-28 18:32 UTC, ashleemboyer approved these changes

2022-10-28 18:49 UTC, merged