feat: license util config
hashicorp/boundary pull request #3248
Opened 2023-05-26 20:12 UTC by mikemountain

2023-05-26 20:35 UTC, johanbrandhorst approved these changes

2023-05-30 14:38 UTC, jefferai commented
For Boundary it makes more sense for this to be in the Controller block...is it mandated or standardized that it lives at the top level?

2023-05-30 16:38 UTC, jefferai approved these changes

2023-05-30 20:09 UTC, johanbrandhorst requested changes

2023-05-30 20:09 UTC, johanbrandhorst commented on internal/daemon/controller/controller.go
>  	"github.com/hashicorp/boundary/internal/auth/ldap"
Nit: import groups

2023-05-30 20:42 UTC, johanbrandhorst approved these changes

2023-05-30 22:20 UTC, merged