Restructuring and addition to permissions docs
hashicorp/boundary pull request #3270
Opened 2023-06-02 21:14 UTC by xingluw

Restructuring and adding of material and examples to permissions/grants documentation. The goal is to make the permissions concept easier to understand and implement for users.

2023-06-02 21:23 UTC, xingluw commented on website/content/docs/concepts/security/permissions/advanced.mdx
> +  Advanced permissions concepts
```suggestion
  Advanced permissions concepts 
```

2023-06-05 14:25 UTC, xingluw commented on website/content/docs/concepts/security/permissions/index.mdx
>  Boundary's permissions model is a composable, RBAC, allow-only model that
Received feedback that this statement may be confusing, especially for an opening sentence in an overview, will edit

2023-06-05 14:33 UTC, Dan-Heath requested changes
This is a huge improvement! I like the way you restructured the content into the grant strings and advanced concept topics. Those seem like smart places to divide up that content, and I think they flow together nicely.

I added some suggestions for style and standards. Also we will need to create a redirect for the deleted file. Please let me know if you have any questions, or if there's anything I can help with.

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/advanced.mdx
> +will match any resource of any type within the scope and allow the given
```suggestion
matches any resource of any type within the scope and allows the given
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/advanced.mdx
> +#### Wildcard ID, Type, and Actions
```suggestion
#### Wildcard ID, type, and actions
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/advanced.mdx
> +substitute the given value into the ID field of the grant string:
```suggestion
A few template possibilities exist, which will 
substitute the given value into the ID field of the grant string at grant evaluation time:
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +- [Output Fields](#output-fields)
```suggestion
- [Output fields](#output-fields)
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +using specific IDs or wildcard IDs and type selectors. There are currently two types of selectors:
```suggestion
You use selectors to indicate which resources the grant should apply to.
Selectors can be specific IDs or wildcard IDs and type selectors. There are currently two types of selectors:
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +  all; this might also be used to grant permissions on collections of resources
```suggestion
  all; it might also be used to grant permissions on collections of resources
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +- An `actions` field indicating which actions to allow the client to perform on
```suggestion
- An `actions` field indicates which actions to allow the client to perform on
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +- An `output_fields` field indicating which top-level fields to return in the
```suggestion
- An `output_fields` field indicates which top-level fields to return in the
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +Grant [examples](#common-grant-examples) can be found at the bottom of this page.
```suggestion
You can find grant [examples](#common-grant-examples) at the bottom of this page.
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +_only_ `output_fields`.
```suggestion
<Note>
`output_fields` is omitted in most examples for brevity, but they are valid
in all of them. It is also valid in each case to omit `actions` and specify
_only_ `output_fields`.
</Note>
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +_only_ `output_fields`.
There is a new format for these admonitions.

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +is "pinned", meaning the permissions will only apply to that resource and subordinate resources.
```suggestion
is "pinned", meaning the permissions only apply to that resource and any subordinate resources.
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +The examples of valid IDs are:
```suggestion
Some examples of valid IDs are:
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/index.mdx
> +that acts as an cheat sheet to help those new to its grant syntax with crafting roles.
```suggestion
that acts as a cheat sheet to help those new to its grant syntax with crafting roles.
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +## Output Fields
```suggestion
## Output fields
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +## Common Grant Examples
```suggestion
## Common grant examples
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +**All Actions**
```suggestion
**All actions** 
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +**View All**
```suggestion
**View all** 
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +**View Targets Only**
```suggestion
**View targets only** 
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +**Connect To Any Target**
```suggestion
**Connect to any target**
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +**Connect To A Specific Target**
```suggestion
**Connect to a specific target** 
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +## General Grant Examples
```suggestion
## General grant examples
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +**Manage All Of 1 Resource Type**
```suggestion
**Manage all of 1 resource type**
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +**View All Of 1 Resource Type**
```suggestion
**View all of 1 resource type**
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +**Manage A Specific Resource IItem**
```suggestion
**Manage a specific resource item**
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/grants.mdx
> +**View A Specific Resource Item**
```suggestion
**View a specific resource item**
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/index.mdx
> +## Grant Strings
```suggestion
## Grant strings
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/index.mdx
> +- Output Fields
```suggestion
- Output fields
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/index.mdx
> +controlled by the role's "grant scope ID" value.
```suggestion
as determined by the role's "grant scope ID" value.
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/permission-grant-formats.mdx
We will have to set up a redirect for this deleted file in the `redirects.js` file. It will be something like:

```json
{
   source: `/boundary/docs/concepts/security/permissions/permission-grant-formats,
   destination: `/boundary/docs/concepts/security/permissions/ ???,
   permanent: true,
},
```

Let me know if you need any help with it.

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/resource-table.mdx
> +# Resource Table
```suggestion
# Resource table
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/index.mdx
> +When a request is made, the scope in which to discover grants is either provided by the client
```suggestion
When a user makes a. request, the scope in which to discover grants is either provided by the client 
```

2023-06-05 14:33 UTC, Dan-Heath commented on website/content/docs/concepts/security/permissions/index.mdx
> +To learn more about Boundary's access management system, see IAM [LINK TBD].
Reminder to replace this placeholder link.

2023-06-05 21:19 UTC, xingluw commented on website/content/docs/concepts/security/permissions/grants.mdx
> +</Note>
```suggestion
```

2023-06-05 21:19 UTC, xingluw commented on website/content/docs/concepts/security/permissions/grants.mdx
> +</Note>
Fixed in 0.13!

2023-06-09 18:11 UTC, xingluw commented on website/content/docs/concepts/security/permissions/advanced.mdx
> +# Advanced Concepts
will add some text in between

2023-06-09 18:13 UTC, xingluw commented on website/content/docs/concepts/security/permissions/advanced.mdx
> +### Wildcard
yeah

2023-06-09 18:13 UTC, xingluw commented on website/content/docs/concepts/security/permissions/advanced.mdx
> +### Wildcard
```suggestion
## Wildcard
```

2023-06-09 18:13 UTC, xingluw commented on website/content/docs/concepts/security/permissions/advanced.mdx
> +#### Wildcard ID
```suggestion
### Wildcard ID
```

2023-06-09 18:14 UTC, xingluw commented on website/content/docs/concepts/security/permissions/advanced.mdx
> +#### Wildcard type
```suggestion
### Wildcard type
```

2023-06-09 18:14 UTC, xingluw commented on website/content/docs/concepts/security/permissions/advanced.mdx
> +#### Wildcard ID and type
```suggestion
### Wildcard ID and type
```

2023-06-09 18:14 UTC, xingluw commented on website/content/docs/concepts/security/permissions/advanced.mdx
> +### Templates
```suggestion
## Templates
```

2023-06-12 13:47 UTC, Dan-Heath approved these changes

2023-06-12 13:47 UTC, stellarsquall approved these changes

2023-06-12 14:04 UTC, merged