docs: Session Recording Requirements for Workers
hashicorp/boundary pull request #3414
Opened 2023-07-12 19:43 UTC by elimt

Clarify the requirements for Boundary workers used for session recording

2023-07-12 21:20 UTC, Dan-Heath requested changes
This is a great addition to this topic, thank you @elimt ! I like breaking these up into AWS and Boundary worker requirements. I suggested some minor copy edits. Please let me know if you have any questions, or if my edits don't make sense.

2023-07-12 21:20 UTC, Dan-Heath commented on website/content/docs/configuration/session-recording/create-storage-bucket.mdx
> +
```suggestion
## Requirements

Before you can create a storage bucket, you must ensure that your environment meets certain requirements.
Session recording requires specific configuration for both the AWS S3 storage bucket and the Boundary worker.

### AWS requirements

```

2023-07-12 21:20 UTC, Dan-Heath commented on website/content/docs/configuration/session-recording/create-storage-bucket.mdx
> +### Boundary Workers Requirements
```suggestion
### Boundary workers requirements
```

2023-07-12 21:20 UTC, Dan-Heath commented on website/content/docs/configuration/session-recording/create-storage-bucket.mdx
> +- A Boundary PKI worker running on darwin, windows or linux. The following binaries are not supported for session recording: nestbsd, openbsd, solaris
```suggestion
[Session recording](/boundary/docs/configuration/session-recording) requires at least one PKI worker that:

- Has access to the AWS S3 storage bucket
- Has an accessible directory defined by `recording_storage_path` for storing session recordings while they are in progress. On session closure, Boundary moves the local session recording to remote storage and deletes the local copy. For more details, refer to [PKI workers](/boundary/docs/configuration/worker/pki-worker#session-recording-hcp-ent).
- Has at least 1 MB of available disk space.
- Runs Darwin, Windows, or Linux. The following binaries are not supported for session recording: NetBSD, OpenBSD, Solaris.
```

2023-07-12 21:20 UTC, Dan-Heath commented on website/content/docs/configuration/session-recording/create-storage-bucket.mdx
> +- A Boundary PKI worker running on darwin, windows or linux. The following binaries are not supported for session recording: nestbsd, openbsd, solaris
I tried to consolidate this bulleted list so we don't have to repeat "A Boundary PKI worker" at the beginning of each line. But please make sure I didn't change the meaning.

2023-07-12 21:27 UTC, AdamBouhmad commented
> This is a great addition to this topic, thank you @elimt ! I like breaking these up into AWS and Boundary worker requirements. I suggested some minor copy edits. Please let me know if you have any questions, or if my edits don't make sense.

To further separate these, do we think it makes sense to split these out into: 

Overview 
Worker Configuration 
Create a storage bucket 
Enable session recording

2023-07-13 13:41 UTC, Dan-Heath commented
> To further separate these, do we think it makes sense to split these out into:
> 
> Overview
> Worker Configuration
> Create a storage bucket
> Enable session recording

Our template for how-to guide procedures like this recommends that we keep pre-requisites in a single location to help readers prepare their environments to perform the tasks described in the topic. I'd be afraid readers might miss those pre-reqs, if we moved them to a new topic.

2023-07-13 15:11 UTC, Dan-Heath approved these changes
This looks great to me, thank you Elim!

2023-07-13 15:59 UTC, merged