feat: Perform asciicast conversion sanity checks
hashicorp/boundary pull request #3481
Opened 2023-07-19 14:53 UTC by elimt

Check that the conversion to asciicast is done on `exec` or `shell` session program. 
Unsupported session programs will throw an error.

2023-07-19 15:05 UTC, elimt commented on internal/bsr/convert/convert.go
> +			if chs.SessionProgram == "" {
Yeah, I agree. That looks cleaner. Moved it as case statement

2023-07-19 15:43 UTC, tmessi requested changes
Looking pretty good.

2023-07-19 15:43 UTC, tmessi commented on internal/bsr/convert/convert.go
> +		chs := ch.Summary.(*ssh.ChannelSummary)
This should either check the type assertion, i.e:

```golang
chs, ok := ch.Summary.(*ssh.ChannelSummary)
if !ok {
  // return error, probably indicating some like an unexpected or malformed bsr.
}
```

```go
switch chs := ch.Summary.(type) {
case *ssh.ChannelSummary:
  switch chs.SessionProgram {
  // rest of switch
default:
  // return an error, probably indicating some like an unexpected or malformed bsr.
```

2023-07-19 15:43 UTC, tmessi commented on internal/bsr/convert/convert.go
> +		chs := ch.Summary.(*ssh.ChannelSummary)
Also, can you add a test case of a BSR that is malformed in this way?

2023-07-19 15:43 UTC, tmessi commented on internal/bsr/convert/convert_test.go
> +	cases := []struct {
Can you include test cases for all of the [valid ssh.SessionPrograms](https://github.com/hashicorp/boundary/blob/456c5dbb4d6c64886abcacb425b7faf5a39de673/internal/bsr/ssh/types.go#L39-L48). It looks like this already has some for `ssh.Exec`, `ssh.Shell` and `ssh.Sumsystem`, so can you add ones for `ssh.None` and `ssh.NotApplicable`?

2023-07-19 15:43 UTC, tmessi commented on internal/bsr/convert/convert.go
> +			}
Can you add some tests that cover the error cases for these?

2023-07-19 16:42 UTC, ddebko approved these changes
This looks good to me.

2023-07-20 10:51 UTC, tmessi approved these changes

2023-07-20 12:13 UTC, irenarindos approved these changes

2023-07-20 13:58 UTC, merged