fix(bsr): limit chunk length
hashicorp/boundary pull request #3500
Opened 2023-07-26 14:48 UTC by irenarindos

Sets a max limit on chunk length to prevent unbounded memory allocation during decoding.

2023-07-26 14:50 UTC, elimt approved these changes

2023-07-26 15:10 UTC, tmessi requested changes

2023-07-27 16:08 UTC, ddebko approved these changes

2023-08-03 14:51 UTC, irenarindos commented
@tmessi changed the limit to 64MB and only enforced on decode, as we talked about

2023-08-03 17:13 UTC, tmessi reviewed
One comment, otherwise looks good to me.

2023-08-03 17:13 UTC, tmessi commented on internal/bsr/chunk.go
> +	MaxChunkLength = 64 * 100 * 1000
I still think this should probably be named something like `MaxChunkDataLength`.

2023-08-03 17:30 UTC, tmessi approved these changes

2023-08-03 17:57 UTC, merged