ICU-10410: add observability tags to plugin protobuf.
hashicorp/boundary pull request #3591
Opened 2023-08-16 16:36 UTC by ajayreshc

Add `eventstream:"observation"` tags to plugin.proto fields.

2023-08-16 16:36 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/boundary?pullRequest=3591)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/boundary?pullRequest=3591)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/boundary?pullRequest=3591).</sub>

2023-08-16 22:40 UTC, sepehrfrgh requested changes

2023-08-16 22:40 UTC, sepehrfrgh commented on internal/proto/controller/api/resources/plugins/v1/plugin.proto
> +  string name = 2; // @gotags: `class:"public" eventstream:"observation"`
`name` field should not be part of the telemetry pipeline since it is customer specified input

2023-08-16 22:51 UTC, johanbrandhorst commented on internal/proto/controller/api/resources/plugins/v1/plugin.proto
> +  string description = 3; // @gotags: `class:"public" eventstream:"observation"`
This is also customer input, I think it should be removed

2023-08-17 16:17 UTC, sepehrfrgh approved these changes
lgtm thanks

2023-08-17 17:07 UTC, johanbrandhorst approved these changes

2023-08-23 17:05 UTC, ajayreshc commented
Closing this PR, will open a new one as I fouled my rebase (not enough coffee error).

2023-08-23 17:05 UTC, closed without merging