Change cache schema from personas to tokens+users
hashicorp/boundary pull request #3737
Opened 2023-09-15 16:14 UTC by talanknight

This PR breaks apart users and tokens.  The cli and the cache daemon's api only operate on tokens and boundary addresses.  The repo keeps the concept of users internal to it and maintains them based on the state of the tokens provided by the caller.  This allows resource refreshes to be performed on a per user basis while allowing the cli to call the api using only the information already present or passed in through env variables or flags (boundary address, keyring type/token names, etc)

In an upcoming PR, when an auth token is first seen by the repo, a call to boundary is made to validate that the user id reported in the auth token is correct before persisting it.  For now we trust the user id reported in the auth token resource stored in the keyring.

2023-09-18 17:47 UTC, jimlambrt approved these changes
One small ref to persona.  Looks great.

2023-09-18 17:47 UTC, jimlambrt commented on internal/cmd/commands/daemon/addtoken.go
> +func (c *AddTokenCommand) AddPersona(ctx context.Context) (*api.Error, error) {
Perhaps just `Add(...)`?

2023-09-18 19:52 UTC, mgaffney requested changes

2023-09-18 19:52 UTC, mgaffney commented on internal/daemon/cache/schema.sql
> +    check (length(id) > 0),
Where does the `id` come from?

2023-09-18 19:52 UTC, mgaffney commented on internal/daemon/cache/schema.sql
> +  user_id text not null
Can the same `auth_token_id` belong to more than one `user_id`?

2023-09-18 19:52 UTC, mgaffney commented on internal/daemon/cache/schema.sql
> +create table if not exists target (
Can you add a comment about what this table contains?

2023-09-18 19:52 UTC, mgaffney commented on internal/daemon/cache/schema.sql
> +create table if not exists session (
Can you add a comment about what this table contains?

2023-09-18 19:52 UTC, mgaffney commented on internal/daemon/cache/schema.sql
> +  id text not null
Where does this `id` come from?

2023-09-18 19:52 UTC, mgaffney commented on internal/daemon/cache/schema.sql
> +  id text not null
Where does this `id` come from?

2023-09-20 18:43 UTC, mgaffney approved these changes
Nice work!

2023-09-21 19:40 UTC, jimlambrt approved these changes
Looks great. Ty for making these changes.

2023-09-21 19:59 UTC, merged