Expose Valid Principals for Vault SSH Signed Certs
hashicorp/boundary pull request #3791
Opened 2023-10-03 00:32 UTC by kheina

This PR allows users to add additional valid principals when creating a vault ssh signed cert credential library.

by default, only the username is passed to vault to sign as a valid principal, but others may be needed in certain use cases. this pr adds `additional_valid_principals` api option and `-additional-valid-principal` cli option to add principals to the `"valid_principals"` vault api request in addition to the required `username` field which is already passed under `"valid_principals"`.

2023-10-04 18:51 UTC, kheina commented on internal/credential/vault/private_library.go
> +	if len(lib.AdditionalValidPrincipals) > 0 {
this should be a check against `""`

carry over from when it was an array

2023-10-04 22:16 UTC, kheina commented on internal/credential/vault/private_library_test.go
> +			}
it actually parses the cert to confirm the valid principals were added! 🎉

2023-10-06 17:40 UTC, tmessi requested changes
I think this is looking good. Can you add some test cases to the [cli tests](https://github.com/hashicorp/boundary/blob/main/internal/tests/cli/boundary/credential_libraries.bats) for setting the new field?

2023-10-10 18:24 UTC, louisruch reviewed
LGTM, agree that we should try add some CLI tests and Tim called out

2023-10-19 18:04 UTC, tmessi approved these changes

2023-10-24 16:44 UTC, merged

2023-12-01 00:18 UTC, jesus-christ666 commented
Ok