Store and use refresh tokens in the client cache
hashicorp/boundary pull request #3857
Opened 2023-10-18 01:50 UTC by talanknight

This PR stores refresh tokens and uses them for subsequent requests.

If the refresh token gets old enough or we detect an invalid refresh token error the refresh token is deleted from the cache.

2023-10-19 20:23 UTC, johanbrandhorst requested changes

2023-10-19 20:23 UTC, johanbrandhorst commented on internal/clientcache/internal/cache/options.go
> +// WithDuration provides an option for specifying a duration
A duration of what? Without any context I don't know what this function does. Could you expand this doc string?

2023-10-19 20:23 UTC, johanbrandhorst commented on internal/clientcache/internal/cache/refresh_test.go
> +// token determines the returned value and is an string representation of an
```suggestion
// token determines the returned value and is a string representation of an
```

2023-10-19 20:23 UTC, johanbrandhorst commented on internal/clientcache/internal/cache/repository_refresh_token.go
> +// to old in which case it does not return a refresh token.
```suggestion
// too old in which case it does not return a refresh token.
```

2023-10-19 20:23 UTC, johanbrandhorst commented on internal/clientcache/internal/cache/repository_refresh_token.go
> +// to old in which case it does not return a refresh token.
Does that mean that it returns an empty string? Or an error? Please expand this comment.

2023-10-19 20:23 UTC, johanbrandhorst commented on internal/clientcache/internal/cache/repository_targets.go
> +
Rogue newline
```suggestion
```

2023-10-19 20:23 UTC, johanbrandhorst commented on internal/refreshtoken/refresh_token.go
> -		return errors.New(ctx, errors.InvalidParameter, op, "refresh token resource type does not match expected resource type")
Could you update the refresh token tests to check for this error code?

2023-10-19 20:23 UTC, johanbrandhorst commented on internal/refreshtoken/refresh_token.go
> -		return errors.New(ctx, errors.InvalidParameter, op, "refresh token resource type does not match expected resource type")
Also note that we probably should add this code to the handlers.ParseRefreshToken function.

2023-10-20 20:45 UTC, johanbrandhorst approved these changes

2023-10-27 21:00 UTC, jimlambrt requested changes
Just one question.  ty!

2023-10-27 21:00 UTC, jimlambrt commented on internal/clientcache/internal/db/schema.sql
> +  update_time timestamp not null default (strftime('%Y-%m-%d %H:%M:%f','now')),
Do we want a trigger for these columns?  See https://github.com/hashicorp/go-kms-wrapping/blob/main/extras/kms/migrations/sqlite/02_version.up.sql

2023-10-27 21:38 UTC, jimlambrt approved these changes
ty!

2023-10-27 21:39 UTC, merged