List pagination schema changes
hashicorp/boundary pull request #3885
Opened 2023-10-23 22:13 UTC by johanbrandhorst

## [sqltest: fix typo](https://github.com/hashicorp/boundary/commit/33821012e55972f32a7c069bc349dedd8603ae5f)

## [internal/db: add deleted tables for all resources](https://github.com/hashicorp/boundary/commit/3ea48bcc4c448c70b5b9f8594762ee496ce6f46d)

Creates a new foo_deleted table for each subtype of each resource that needs to support pagination. The deleted
tables are used to track deletions of resources and return them to users of the new pagination API. We track only the ID and delete_time of the resource, so there's no way to filter out resources that the user could not see before it was deleted. This is intentional to keep the design simple and is not considered a security issue.

2023-10-23 22:19 UTC, johanbrandhorst commented
Note that the schema diff job seems to break because this diff is too large 😬. Hopefully it's still easy enough to read without the diff.

2023-10-24 17:55 UTC, tmessi commented
> Note that the schema diff job seems to break because this diff is too large 😬. Hopefully it's still easy enough to read without the diff.

See: https://github.com/hashicorp/boundary/pull/3909

2023-10-24 17:59 UTC, tmessi commented
> Note that the schema diff job seems to break because this diff is too large 😬. Hopefully it's still easy enough to read without the diff.

I would also note that since this is all new tables and functions, the diff isn't as useful. Although it would help catch if something was accidentally being altered.

2023-10-25 10:50 UTC, jimlambrt approved these changes

2023-10-25 13:28 UTC, tmessi requested changes
Can you update `internal/db/sqltests/tests/Makefile` so the new tests run in CI? They are failing for me when I run them manually.

You need to add the new directory to the list of tests here: 

https://github.com/hashicorp/boundary/blob/752f20fa276f029d1f7d5a36820e9929abc0446f/internal/db/sqltest/Makefile#L20-L35

2023-10-25 14:55 UTC, mgaffney approved these changes

2023-10-25 14:55 UTC, mgaffney commented on internal/db/sqltest/tests/purge/trigger_insert_on_delete.sql
> +
```suggestion

```
Delete trailing whitespace

2023-10-25 14:55 UTC, mgaffney commented on internal/db/sqltest/tests/purge/trigger_insert_on_delete.sql
> +
```suggestion

```
Delete trailing whitespace

2023-10-25 16:48 UTC, johanbrandhorst commented
@tmessi thanks for spotting that, looks like we missed the renaming of the trigger.

2023-10-25 18:47 UTC, tmessi approved these changes

2023-10-25 18:47 UTC, tmessi commented on internal/db/sqltest/tests/purge/deleted_table_tests.sql
> +  $$ language sql;
```suggestion
  $$ language sql;
```

2023-10-25 18:50 UTC, merged