Create repository facotry for apptoken
hashicorp/boundary pull request #3936
Opened 2023-10-26 16:12 UTC by uruemu

2023-10-26 17:42 UTC, cameronperera approved these changes
LGTM

2023-10-27 14:42 UTC, jimlambrt commented
Can you rebase so it only includes the new commits?

2023-10-27 15:03 UTC, jimlambrt requested changes
Looks great, one minor bit.

2023-10-27 15:03 UTC, jimlambrt commented on internal/apptoken/options.go
> +func WithLimit(_ context.Context, limit int) Option {
unit test?

2023-10-27 15:07 UTC, uruemu commented on internal/apptoken/options.go
> +func WithLimit(_ context.Context, limit int) Option {
Added a test!

2023-11-04 11:56 UTC, merged