Change session list queries to avoid using the session_list view
hashicorp/boundary pull request #4095
Opened 2023-12-04 21:31 UTC by mikemountain

2023-12-04 23:31 UTC, johanbrandhorst requested changes

2023-12-04 23:31 UTC, johanbrandhorst commented on internal/session/query.go
> +          swp.worker_id,
As @tmessi mentioned, it seems we could drop this from the query as it's not used in constructing the session: https://github.com/hashicorp/boundary/blob/da5dd383ad08d3977bdf94a40158526238b0f514/internal/session/repository.go#L143-L164. That means we could drop the whole `session_worker_protocols` CTE. Could you do a pass over the other columns here and see if there's anything else we can drop?

2023-12-05 15:43 UTC, johanbrandhorst approved these changes
🎉 nice!

2023-12-05 16:11 UTC, tmessi requested changes
I think we should also update the [`sessionListView` struct](https://github.com/hashicorp/boundary/blob/e108fd32d0ca2aedc4a79caeaf7ae08d2f6561fe/internal/session/session.go#L567-L596) to:

- Remove `ProtocolWorkerId` since it is now not being populated, and does not seem to be used anywhere already.
- Rename it since it is no longer used with a view.

2023-12-12 00:42 UTC, johanbrandhorst requested changes
See my comment

2023-12-15 22:36 UTC, johanbrandhorst commented on internal/db/schema/migrations/oss/postgres/80/10_session_base_table_updates.up.sql
> +commit;
Do you need to add/update the session index SQL test?

2023-12-18 22:18 UTC, johanbrandhorst approved these changes
LGTM, thanks!

2024-01-09 19:14 UTC, johanbrandhorst requested changes
Lets wait with merging this until we have performed all the session performance tests.

2024-01-10 22:37 UTC, johanbrandhorst approved these changes

2024-01-11 14:56 UTC, tmessi approved these changes

2024-01-11 17:45 UTC, merged