fix(db): make bucket_prefix column immutable for storage buckets
hashicorp/boundary pull request #4108
Opened 2023-12-06 05:34 UTC by ddebko

# Summary

The storage domain does not allow the storage bucket prefix value to be mutated during an update action because it is not supported in the mask. However the column is mutable when directly interacting with the database table. This PR updates the `immutable_columns` trigger on the `storage_plugin_storage_bucket` table to include `bucket_prefix`.

2023-12-06 14:58 UTC, elimt approved these changes

2023-12-06 17:29 UTC, mgaffney requested changes

2023-12-06 17:29 UTC, mgaffney commented on internal/db/schema/migrations/oss/postgres/80/01_storage_bucket.up.sql
> +drop trigger if exists immutable_columns ON storage_plugin_storage_bucket;
```suggestion
drop trigger immutable_columns on storage_plugin_storage_bucket;
```
The trigger should exist and ff it doesn't we want to error out.

2023-12-06 17:29 UTC, mgaffney commented on internal/db/schema/migrations/oss/postgres/80/01_storage_bucket.up.sql
> +    for each row execute procedure immutable_columns('public_id', 'scope_id', 'create_time', 'bucket_name', 'bucket_prefix');
Please fix the indentation to follow our style guide

2023-12-20 22:34 UTC, mgaffney approved these changes

2024-01-02 16:53 UTC, merged