docs: Update release notes with fixes
hashicorp/boundary pull request #4192
Opened 2023-12-20 22:23 UTC by Dan-Heath

The Boundary 0.14.1 and 0.13.5 releases contained a CVE fix for Go that was not documented. It should be added to the release notes.

2024-01-02 22:52 UTC, AdamBouhmad requested changes

2024-01-02 22:52 UTC, AdamBouhmad commented on website/content/docs/release-notes/v0_13_0.mdx
> +Community users should upgrade to version 0.14.1 or later.
Quick note here that to use a community version with the fix, users will need to upgrade to 0.14.3, as 0.14.1 uses [go version 1.21.3](https://github.com/hashicorp/boundary/blob/release/0.14.1/.go-version)

2024-01-02 22:52 UTC, AdamBouhmad commented on website/content/docs/release-notes/v0_14_0.mdx
> +
At the moment, we note that 0.14.1 includes a bumped version of GO(1.21.5), however 0.14.1 was only bumped to what was available at the time, 1.21.3. Boundary 0.14.3 includes a bump to GO 1.21.5. I've Modified the following from the changelog for reference: 

**0.14.1** 
* deps: Bump Go version to v1.21.3; gRPC to v1.58.3; golang.org/x/net to
  v0.17.0. This is to address a security vulnerability in the HTTP stack where a
  malicious HTTP/2 client which rapidly creates requests and immediately resets
  them can cause excessive server resource consumption.
* Go CVE-2023-39325 & Go CVE-2023-39326

**0.14.3:** 
* deps: Bump Go version to v1.21.5. This is to address multiple security
  vulnerabilities, including a fix in net/http to limit
  chunked data overhead. See https://groups.google.com/g/golang-announce/c/iLGK3x6yuN
* CVE 2023-39322 & CVE 2022-45285

2024-01-03 16:05 UTC, Dan-Heath commented on website/content/docs/release-notes/v0_14_0.mdx
> +
Thank you for the clarification here! I think I updated this file accordingly, but the link the Google group conversation for the 0.14.3 fix was broken. So I included the links to the GitHub advisories for CVE-2023-39322 & CVE-2022-45285 instead.

2024-01-03 18:33 UTC, psekar approved these changes

2024-01-03 19:00 UTC, stellarsquall commented on website/content/docs/release-notes/v0_14_0.mdx
> +    (Fixed in 0.14.3 and 0.13.5 HCP/ENT)
for consistency

```suggestion
    (Fixed in 0.14.3 and 0.13.5 <sup>HCP/ENT</sup>)
```

2024-01-03 19:13 UTC, Dan-Heath commented on website/content/docs/release-notes/v0_14_0.mdx
> +    (Fixed in 0.14.3 and 0.13.5 HCP/ENT)
Thanks Robin, good catch!

2024-01-03 19:18 UTC, stellarsquall approved these changes

2024-01-03 22:09 UTC, merged