Add alias schema changes
hashicorp/boundary pull request #4230
Opened 2024-01-12 00:51 UTC by talanknight

This PR adds a postgres extension citext which allows us to have aliases be enforced unique in a case-insensitive way.

While aliases will eventually be allowed in any scope, right now the fk constraint enforces that aliases are only created in the global scope.  The alias_scope_is_parent_to_destination_scope function still is created in a way to allow non global scopes to be used by the alias.

2024-01-23 20:42 UTC, irenarindos requested changes

2024-01-23 20:42 UTC, irenarindos commented on CHANGELOG.md
> +* postgres citext dependency added to enable aliases to be globally unique
Should this PR also update the system-requirements website doc to include this dependency?

2024-01-23 20:42 UTC, irenarindos commented on internal/db/schema/migrations/oss/postgres/82/01_citext_extension.up.sql
> +  create extension citext;
If we want to add the citext extension the same way we did for [pgcrypto](https://github.com/hashicorp/boundary/blob/main/internal/db/schema/migrations/oss/postgres/0/60_wh_domain_types.up.sql#L6):
```suggestion
  create extension if not exists "citext";
```

2024-01-23 20:42 UTC, irenarindos commented on internal/db/schema/migrations/oss/postgres/82/04_alias_target.up.sql
> +  create trigger insert_alias_target_deleted after delete on alias_target
I think this needs to be `insert_deleted_id` - The pgtap tests are failing with
```
/test/purge/deleted_table_tests.sql ..................................................... 1/363 
 Failed test 362: "Table alias_target should have trigger insert_deleted_id"
 Failed test 363: "Trigger insert_deleted_id should call insert_deleted_id()"
         have: NULL
         want: insert_deleted_id
 Looks like you failed 2 tests of 363
```

2024-01-23 20:42 UTC, irenarindos commented on internal/db/sqltest/tests/alias/wt_target_alias.sql
> +  prepare label_to_long as insert into target_alias_testing (v) values
Nit: to -> too here and in the tests below
```suggestion
  prepare label_too_long as insert into target_alias_testing (v) values
```

2024-01-24 13:13 UTC, irenarindos requested changes
Looks good, just two minor things!

2024-01-24 13:13 UTC, irenarindos commented on website/content/docs/install-boundary/system-requirements.mdx
> +Boundary has a dependency on the PostgreSQL [pgcrypto](https://www.postgresql.org/docs/11/pgcrypto.html) module and [citext](https://www.postgresql.org/docs/11/citext.html), which are part of the sta
```suggestion
Boundary has a dependency on the PostgreSQL [pgcrypto](https://www.postgresql.org/docs/11/pgcrypto.html) module and [citext](https://www.postgresql.org/docs/11/citext.html), which are part of the standard modules that are supplied with PostgreSQL.
```

2024-01-24 13:13 UTC, irenarindos commented on internal/db/sqltest/tests/alias/targets.sql
> +
Should there also be a test around the destination id being set when host id is set?

2024-01-25 20:14 UTC, mgaffney requested changes

2024-01-29 16:57 UTC, irenarindos commented on internal/db/schema/migrations/oss/postgres/82/01_citext_extension.up.sql
> +-- Copyright (c) HashiCorp, Inc.
Just dropping a note that these need to be moved from 82 to 84

2024-01-31 17:37 UTC, mgaffney approved these changes

2024-01-31 17:43 UTC, merged