docs: Update release notes
hashicorp/boundary pull request #4281
Opened 2024-01-24 21:46 UTC by Dan-Heath

2024-01-30 21:48 UTC, johanbrandhorst requested changes
Note that the changelog (which this might be sourced from?) will be updated one final time after the promotion to production.

2024-01-31 00:03 UTC, johanbrandhorst approved these changes

2024-01-31 00:57 UTC, psekar approved these changes

2024-01-31 00:57 UTC, psekar commented on website/content/docs/release-notes/v0_15_0.mdx
> +    If you have session recording configured, you must update your IAM policy in AWS before you upgrade to release 0.15.0 to ensure your session recordings continue to get uploaded to S3. The IAM pol
This policy change should happen before customers upgrade their worker to 0.15.0.

2024-01-31 01:01 UTC, stellarsquall approved these changes

2024-01-31 01:23 UTC, merged