testing/e2e: add auth method pagination tests
hashicorp/boundary pull request #4333
Opened 2024-01-31 16:40 UTC by mikemountain

2024-01-31 16:42 UTC, johanbrandhorst requested changes

2024-01-31 16:42 UTC, johanbrandhorst commented on testing/internal/e2e/tests/base/auth_method_password_test.go
> +// TestCliPaginateAuthMethods asserts that the CLI autamatically paginates to retrieve
```suggestion
// TestCliPaginateAuthMethods asserts that the CLI automatically paginates to retrieve
```

2024-01-31 16:42 UTC, johanbrandhorst commented on testing/internal/e2e/tests/base/auth_method_password_test.go
> +	numPrecreatedAuthMethods := 3
Are there? It seems to not be the case in the API test below.

2024-01-31 20:54 UTC, moduli requested changes

2024-01-31 20:54 UTC, moduli commented on testing/internal/e2e/tests/base/auth_method_password_test.go
> +	require.Len(t, initialAuthMethods.Items, c.MaxPageSize+1)
Looks like the test is currently failing here
```
should have 11 item(s), but has 9
```

2024-01-31 21:37 UTC, johanbrandhorst approved these changes
LGTM if the tests pass

2024-02-01 14:40 UTC, moduli commented on testing/internal/e2e/tests/base/auth_method_password_test.go
> +	require.Len(t, initialAuthMethods.Items, c.MaxPageSize+1)
It has been resolved now

2024-02-01 15:01 UTC, moduli commented on testing/internal/e2e/tests/base/auth_method_password_test.go
> +			"-recursive",
Does this need the `-recursive` flag?

2024-02-01 15:02 UTC, moduli commented on testing/internal/e2e/tests/base/auth_method_password_test.go
> +			"-recursive",
Does this need the `-recursive` flag?

2024-02-01 15:03 UTC, moduli commented on testing/internal/e2e/tests/base/auth_method_password_test.go
> +	initialAuthMethods, err := amClient.List(ctx, newOrgId, authmethods.WithRecursive(true))
Does this need the `WithRecursive` option>

2024-02-01 15:04 UTC, moduli commented on testing/internal/e2e/tests/base/auth_method_password_test.go
> +	newAuthMethods, err := amClient.List(ctx, newOrgId, authmethods.WithListToken(initialAuthMethods.ListToken), authmethods.WithRecursive(true))
Does this need the `WithRecursive` option?

2024-02-01 17:46 UTC, merged