Use the intercepted token always. If the keyring matches, use it from there
hashicorp/boundary pull request #4355
Opened 2024-02-02 01:16 UTC by talanknight

This PR fixes a number of issues with the way we currently add tokens to the client cache daemon.

Previously, If a keyring is not present on the platform the user must specify `-keyring-type none` when calling `boundary daemon add-token`, With this PR it will treat the platform not having a keyring it knows about as if the user provided the keyring-type none.

Previously, if a user called `boundary authenticate -format json` the returned token would not be added to the client cache. With this PR it is intercepted and added.

2024-02-02 14:44 UTC, moduli reviewed
The test is still failing here
```
_, err = te.Boundary.Resource.Exec(
[]string{
	"boundary", "authenticate", "password",
	"-addr", te.Boundary.UriNetwork,
	"-auth-method-id", te.DbInitInfo.AuthMethod.AuthMethodId,
	"-login-name", te.DbInitInfo.AuthMethod.LoginName,
	"-password", "env://E2E_TEST_BOUNDARY_PASSWORD",
	"-keyring-type", "none",
	"-format", "json",
},
dockertest.ExecOptions{
	StdOut: buf,
	StdErr: ebuf,
	Env:    []string{"E2E_TEST_BOUNDARY_PASSWORD=" + te.DbInitInfo.AuthMethod.Password},
},
)
require.NoError(t, err)
```
for the following reason

```
migration_test.go:355: 
│         	Error Trace:	/home/runner/work/boundary/boundary/testing/internal/e2e/tests/database/migration_test.go:355
│         	            				/home/runner/work/boundary/boundary/testing/internal/e2e/tests/database/migration_test.go:54
│         	Error:      	Should be empty, but was Error opening keyring: Specified keyring backend not available
│         	            	Token must be provided via BOUNDARY_TOKEN env var or -token flag. Reading the token can also be disabled via -keyring-type=none.
```

2024-02-02 22:48 UTC, moduli commented
Oh, right. Because of the way this test is structured, it starts with the most recently released version of Boundary (i.e. 0.15.0) and populates its database using that version before trying to migrate it to the current working branch. The failure is happening during that population stage, so it wouldn't get these changes until we release the next version...

2024-02-05 11:01 UTC, jimlambrt requested changes
I few minor grammar/typo bits.  I did ask one question about what to do when the client token and the keyring token are not equal that I think might be important.

2024-02-06 19:44 UTC, jimlambrt approved these changes
ty!

2024-02-06 19:45 UTC, merged