Add ListResolvableAliases to the user service
hashicorp/boundary pull request #4609
Opened 2024-04-05 22:58 UTC by talanknight

There are a few non common ways this method uses our ACL and grant system. A user is able to list resolvable aliases for another user if they are granted permission to do so. That means we had to load the grants for the user being listed for anot not the requester when determining if an alias is able to resolve to a destination for which the requested user has permission.

Similarly, the grant hash used for the list pagination is required to be that of the user being listed and not the requester.

Note: This follows the approach we have taken with the original pagination of aliases and has put off generalizing the pagination logic to generic alias type and instead implements it for the specific target subtype for the sake of speed of implementation, and because it is still unclear what benefit any other type of alias would have yet and if we'll ever get to there.  If we decide to implement another subtype of alias, the existing pagination logic will need to be refactored anyways at which time this same logic would be easier to refactor as well.

2024-04-08 19:51 UTC, moduli commented on internal/alias/target/service_list_resolvable_ext_test.go
> +			_, err = target.ListResolvableAliasesPage(ctx, nil, 1, filterFunc, tok, repo, byIdPerms)
Yea. Agreed with Todd here. We only needed to fix tests that only had one use of `err`, but didn't use `:=`

Like...
```
t.Run("nil repo", func(t *testing.T) {
	t.Parallel()
	_, err := target.ListResolvableAliases(ctx, []byte("some hash"), 1, nil, byIdPerms)
	require.ErrorContains(t, err, "missing repo")
})
```

2024-04-08 19:54 UTC, johanbrandhorst commented on internal/alias/target/service_list_resolvable_ext_test.go
> +			_, err = target.ListResolvableAliasesPage(ctx, nil, 1, filterFunc, tok, repo, byIdPerms)
Ah, good shout

2024-04-08 19:55 UTC, johanbrandhorst commented on internal/alias/target/service_list.go
> +	filterItemFn pagination.ListFilterFunc[*Alias],
Haha, sorry for the confusion, of course this package wouldn't actually use a function from the handler package 😅 .

2024-04-08 19:56 UTC, johanbrandhorst approved these changes

2024-04-16 20:05 UTC, jimlambrt requested changes
minor questions

2024-04-16 20:31 UTC, jimlambrt approved these changes
ty!

2024-04-17 15:26 UTC, merged