Add observation tags for Session Recording Service
hashicorp/boundary pull request #4825
Opened 2024-05-23 21:01 UTC by uruemu

Adds observation tags to fields Session Recording Servicemessages.

2024-05-23 21:05 UTC, johanbrandhorst requested changes

2024-05-23 21:05 UTC, johanbrandhorst commented on internal/proto/controller/api/resources/sessionrecordings/v1/session_recording.proto
>    resources.scopes.v1.ScopeInfo scope = 2; // @gotags: class:"public"
Nit: we can remove this `class` tag

2024-05-23 21:05 UTC, johanbrandhorst commented on internal/proto/controller/api/resources/sessionrecordings/v1/session_recording.proto
> +  HostCatalog host_catalog = 2 [json_name = "host_catalog"]; // @gotags: class:"public" eventstream:"observation"
I don't think this will have any effect (`HostCatalog` is a message type). Both the `class` and `eventstream` tags can be removed, I think.

2024-05-23 21:05 UTC, johanbrandhorst commented on internal/proto/controller/api/resources/sessionrecordings/v1/session_recording.proto
>    CredentialStore credential_store = 2 [json_name = "credential_store"]; // @gotags: class:"public"
Nit: we could remove this `class` tag.

2024-05-23 21:05 UTC, johanbrandhorst commented on internal/proto/controller/api/resources/sessionrecordings/v1/session_recording.proto
>    CredentialStore credential_store = 2 [json_name = "credential_store"]; // @gotags: class:"public"
Ditto

2024-05-23 21:05 UTC, johanbrandhorst commented on internal/proto/controller/api/services/v1/session_recording_service.proto
> +  uint32 page_size = 4 [json_name = "page_size"]; // @gotags: `class:"public"` eventstream:"observation"
This should either use ` consistently or not. I prefer not:
```suggestion
  uint32 page_size = 4 [json_name = "page_size"]; // @gotags: class:"public" eventstream:"observation"
```

2024-05-23 21:05 UTC, johanbrandhorst commented on internal/proto/controller/api/services/v1/session_recording_service.proto
> +  string response_type = 2 [json_name = "response_type"]; // @gotags: `class:"public"` eventstream:"observation"
Ditto, lets just remove the ` in this file.

2024-05-23 21:12 UTC, uruemu commented
@johanbrandhorst PTAL. Addressed your comments

2024-05-24 00:25 UTC, sepehrfrgh approved these changes
LGTM thanks Uruemu

2024-05-24 15:30 UTC, merged