implement configurable getDownstreamWorker timeout
hashicorp/boundary pull request #5007
Opened 2024-08-12 17:51 UTC by bosorawis

2024-08-12 20:17 UTC, johanbrandhorst approved these changes

2024-08-12 20:46 UTC, johanbrandhorst requested changes
Actually lets add some tests 😁

2024-08-13 01:21 UTC, bosorawis commented
> Actually lets add some tests 😁

added tests!

2024-08-13 20:02 UTC, johanbrandhorst approved these changes

2024-08-13 21:27 UTC, merged