docs: Update session recording docs with asciicast info
hashicorp/boundary pull request #5072
Opened 2024-09-04 18:34 UTC by Dan-Heath

ICU-15008 document ToB findings regarding using asciicast for session recording.

2024-09-04 19:08 UTC, louisruch requested changes
This looks great other than the warnings that we currently do not display but is something we want to still do.

2024-09-04 19:08 UTC, louisruch commented on website/content/docs/operations/session-recordings/index.mdx
> +Boundary displays a warning when a user provides multiple environment requests to set the shell variable.
We do not currently provide this warning, this is something we want to still do

2024-09-04 19:08 UTC, louisruch commented on website/content/docs/operations/session-recordings/index.mdx
> +Boundary displays a warning when a request that is recorded in the BSR file is not included in the asciicast.
Again we do not currently display this warning

2024-09-04 19:08 UTC, louisruch commented on website/content/docs/operations/session-recordings/index.mdx
> +Boundary displays a warning when a request that is recorded in the BSR file is not included in the asciicast.
Same

2024-09-04 19:35 UTC, Dan-Heath commented
> This looks great other than the warnings that we currently do not display but is something we want to still do.

Thanks for the review @louisruch ! I removed those 3 mentions of the warnings:

https://boundary-4o7k6eaa6-hashicorp.vercel.app/boundary/docs/operations/session-recordings#security

2024-09-04 21:05 UTC, stellarsquall approved these changes

2024-09-04 22:18 UTC, louisruch approved these changes

2024-09-05 14:18 UTC, elimt approved these changes

2024-09-05 16:09 UTC, merged