Delete terminated sessions in batches
hashicorp/boundary pull request #5201
Opened 2024-10-23 20:36 UTC by mgaffney

This PR:

* adds retries to `scheduler.JobStatus`
* adds a new `batch` package under the `scheduler` package
* uses the new `batch` package to delete terminated sessions in batches

2024-10-24 20:19 UTC, tmessi requested changes

2024-10-24 21:10 UTC, johanbrandhorst approved these changes
LGTM!

2024-10-24 23:13 UTC, mgaffney commented on internal/scheduler/job.go
> +	// configurable amount of time.
Do you mean the `Scheduler` structs `interruptThreshold` field?

2024-10-24 23:21 UTC, mgaffney commented on internal/scheduler/batch/batch.go
> +	StatusThreshold time.Duration
The StatusThreshold is actually set by the job scheduler. I'm only trying to cover the zero value and the odd case that someone puts in a negative number.

2024-10-25 14:06 UTC, mgaffney commented on internal/scheduler/job.go
> +	// configurable amount of time.
I updated the comment

2024-10-25 14:13 UTC, tmessi approved these changes

2024-10-25 14:28 UTC, merged