chore: update go dependency
hashicorp/boundary pull request #5303
Opened 2024-12-03 18:26 UTC by ddebko

2024-12-03 18:28 UTC, johanbrandhorst approved these changes

2024-12-03 18:30 UTC, johanbrandhorst requested changes
Hm, make gen is failing

2024-12-03 18:49 UTC, johanbrandhorst submitted a review, later dismissed

2024-12-03 19:04 UTC, moduli reviewed
Dumb question... does this actually contain the change to the awssdk that we're looking for?

2024-12-04 18:10 UTC, johanbrandhorst approved these changes

2024-12-04 18:58 UTC, merged