ensure make tools executes before build-ui
hashicorp/boundary pull request #683
Opened 2020-10-14 19:29 UTC by mootpt

`make dev` requires `build-ui` which executes a script that requires `go-bindata` binary that isn't installed without executing `make tools`. This pr requires the `tools` make target is executed first.

2020-10-14 19:29 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/boundary?pullRequest=683)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/boundary?pullRequest=683)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/boundary?pullRequest=683).</sub>

2020-10-14 19:39 UTC, malnick commented
Thanks @mootpt - this looks great.

2020-10-14 19:40 UTC, malnick approved these changes

2020-10-14 19:44 UTC, malnick requested changes
@mootpt - Second pass on this, I thought you added it to the `dev` step. Since this isn't UI specific, I think it's more appropriate to add it to the `dev` target, which inevitably runs the `build-ui` target.

2020-10-14 19:47 UTC, mootpt commented
got it. fixing

2020-10-14 19:49 UTC, mootpt commented
@malnick should be all set.

2020-10-14 19:53 UTC, mootpt commented
@malnick actually you sure you don't want it in build-ui step? That step executes `go-bindata` which is unavailable unless tools are installed

2020-10-14 20:05 UTC, jefferai requested changes
We specifically chose not to run `tools` for `dev` because it installs binaries and may overwrite (or hide, via being further up in PATH) versions of binaries that you want to stay installed.

A better approach might be to separate out the step that runs go-bindata on the assets that result after building the UI, and then if that fails, print out something suggesting running `make tools`, but with a warning that this may replace binaries they already have on the system.

I realize this is a chicken and egg issue because then you'd have to go through the UI build again. Open to better suggestions!

2020-10-14 20:10 UTC, jefferai commented
Also, hi @mootpt !!

2020-10-14 20:13 UTC, jefferai commented
Perhaps if go-bindata is the only tool we need after the build step, we can simply attempt to find or invoke it before build-ui and if it doesn't exist, we prompt the user to install it or run `make tools` with appropriate caveats?

2020-10-14 20:29 UTC, jack1902 commented
https://github.com/hashicorp/boundary/blob/f008dff9eba362e3ea7e54c93c853f3b15411c06/scripts/build.sh#L52 

`gox` is also required as part of `make dev`. Prehaps just mentioning you _might_ need to run `make tools`  in the README might help?

2020-10-15 17:15 UTC, mootpt commented
yup. I'll just add to README

2020-10-15 17:46 UTC, jefferai approved these changes
I wordsmithed it a little, but looks good -- thanks!

2020-10-15 17:46 UTC, merged