Update ui build to use 'admin' folder instead of 'core'
hashicorp/boundary pull request #792
Opened 2020-11-17 23:27 UTC by gsusmi

Post release of v0.1.2, ui/core folder has been renamed to ui/admin.
Update ui build scripts to be aware of the path change.

@samsalisbury , I wasn't able to figure out how to update folder path reference in `packages-oss.lock`. Is there a command I should be running to get it updated? Appreciate your help in figuring this out.

packages-oss.lock/pkgs.yml
```
724:          && UIDIR="$DIR/ui/core/dist" \
```
should read:
```
724:          && UIDIR="$DIR/ui/admin/dist" \
```

2020-11-17 23:28 UTC, gsusmi commented on internal/ui/VERSION
> +b7937e77ad5a37fcf0bf0ed2b6d4e4b34d97b144 Merge pull request #383 from hashicorp/rename-core-to-admin
Bumped up ui commit to latest to pick up folder change in boundary-ui repo.

2020-11-18 12:25 UTC, samsalisbury commented
Hi @gsusmi yes, after modifying the spec file `packages-oss.yml` you need to run `make packages` to regenerate the build system and CI config. I will send you links to documentation on Slack.

2020-11-18 12:36 UTC, samsalisbury requested changes
Needs `make packages` running as discussed, thanks!

2020-11-18 17:09 UTC, gsusmi commented
Update includes .circleci and package-oss.lock changes after running `make packages`.

2020-11-18 20:06 UTC, samsalisbury approved these changes
:shipit:

2020-11-18 21:29 UTC, merged