ICU-743/Domain errors internal/kms refactor
hashicorp/boundary pull request #848
Opened 2021-01-05 20:42 UTC by louisruch

### What does this PR do

Refactors internal/kms package to use new domain errors

2021-01-05 23:11 UTC, louisruch commented
@talanknight @jimlambrt @mgaffney PTAL

2021-01-06 18:16 UTC, talanknight requested changes
Looks good!

2021-01-06 18:30 UTC, louisruch commented on internal/kms/repository_database_key_version.go
> +	const op = "kms.(Repository).ListDatabaseKeyVersions"
Yes, it was decided after the host refactor, I have been tempted to go back and change it, the reason I have not is the same argument that can be made for not adding `.(Repository).` here; it does not add needed context.  

The reason we added the `.(X).`  was for interfaces, you will see in this PR we have `Encrypt`, `Decrypt` and `VetForWrite` all within the `kms` package but implemented a number of times.  I added repository as a habit but I am not sure if we want to that be the standard or if we only want to use `.(X).` for interfaces

2021-01-06 18:34 UTC, louisruch commented on internal/kms/repository_database_key_version.go
> +	const op = "kms.(Repository).ListDatabaseKeyVersions"
To me it seems simpler to rather adopt the `.(X).` notation to avoid conflict moving forward

2021-01-06 18:36 UTC, louisruch commented on internal/kms/oplog_key_version.go
> +		return errors.New(errors.InvalidParameter, op, "missing private id")
I have been implementing it as such so far, any alternative suggestion?

2021-01-08 22:28 UTC, talanknight commented on internal/kms/oplog_key_version.go
> +		return errors.New(errors.InvalidParameter, op, "missing private id")
No great suggestions.  I've just ran into similar issues when thinking about errors for database schema management and was hoping to hear more ideas about this.  

When the receiver is not in a good state it feels more like a precondition or a struct initialization failure more than a  parameter failure sometimes but in this case I think the current code fits fine.

2021-01-08 22:28 UTC, talanknight approved these changes
Looks good.  Just 1 minor comment.

2021-01-12 12:14 UTC, jimlambrt approved these changes
Looks great.

2021-01-12 16:50 UTC, merged